### ISSUE TITLE
群晖docker一直无法下载源文件 curl: (28) Resolving timed out after 3000 millisecond，日志也附上了

### ISSUE THREAD

**Issue by Saolence** [P3TERX/Aria2-Pro-Docker#101]
[p3terx-aria2-pro1.csv](https://github.com/P3TERX/Aria2-Pro-Docker/files/9751319/p3terx-aria2-pro1.csv)

**Comment by yilin101** [comment]
一样的  文件下载上传了 还是提示 


[ERROR] 'core' download error, retry ...


[INFO] Downloading 'core' ...

curl: (28) Resolving timed out after 3000 milliseconds

curl: (28) Resolving timed out after 3000 milliseconds

curl: (28) Resolving timed out after 3000 milliseconds


[ERROR] 'core' download error, retry ...


[INFO] Downloading 'core' ...

curl: (28) Resolving timed out after 3000 milliseconds

curl: (28) Resolving timed out after 3000 milliseconds

curl: (28) Resolving timed out after 3000 milliseconds


[ERROR] 'core' download error, retry ...


[INFO] Downloading 'core' ...

curl: (28) Resolving timed out after 3000 milliseconds

**Comment by P3TERX** [comment]
#49
