### ISSUE TITLE
Aria2  Pro 无法使用IPv6连接使用

### ISSUE THREAD

**Issue by PeelSign** [P3TERX/Aria2-Pro-Docker#104]

**Comment by jackadam1981** [comment]
host模式也没搞定，docker配置ipv6，也没搞定。
同求解决方案。

**Comment by jackadam1981** [comment]
[docker compose ipv6的处理 容器互联的方法](https://www.cnblogs.com/jackadam/p/16617369.html)

**Comment by PeelSign** [comment]
> [docker compose ipv6的处理 容器互联的方法](https://www.cnblogs.com/jackadam/p/16617369.html)

通过开启host模式，在配置中开启IPV6设置（默认设置是关闭的~）
