### ISSUE TITLE
可能是一个bug，时间戳不更新

### ISSUE THREAD

**Issue by bfcs** [P3TERX/Aria2-Pro-Docker#105]
环境：
win11， docker-desktop部署

描述：
在2022年10月30号，通过RPC下载一个日期为2022年4月20的b站视频
![image](https://user-images.githubusercontent.com/52602045/198861989-dc73ad43-1992-463c-bc28-40c103f6073a.png)

存储在文件管理器中，日期为2022年4月20，而不是2022年10月30
![image](https://user-images.githubusercontent.com/52602045/198862032-b0975269-379e-4775-b6ea-b85797f09550.png)

这和直觉不符，通常，下载一个文件，最开始的时间应该为下载的时间

**Comment by bfcs** [comment]
![image](https://user-images.githubusercontent.com/52602045/198862095-e0fcc038-3bbc-4d3f-851f-230577e85306.png)

**Comment by bfcs** [comment]
![image](https://user-images.githubusercontent.com/52602045/198862101-f4b64cfe-589e-4fe8-81f9-382760644a42.png)

**Comment by XIAOCHEN-NYE** [comment]
请问找到解决问题了么？，我也想解决此问题，它严重影响了我查找文件的效率

**Comment by XIAOCHEN-NYE** [comment]
我找到办法了找到aria2.conf（配置文件）更改remote-time [true|false][¶](https://aria2.github.io/manual/en/html/aria2c.html#cmdoption-R) t为开启 f关闭

**Comment by XIAOCHEN-NYE** [comment]
https://aria2.github.io/manual/en/html/aria2c.html
