### ISSUE TITLE
Proxy RPC over HTTPS with Nginx Not Working

### ISSUE THREAD

**Issue by Saroufim** [P3TERX/Aria2-Pro-Docker#21]
Hello. 

The RPC daemon connects normally when using the IP address but when it is proxied over nginx, it doesn't connect at all. Here's my subfolder config:
```

location /aria/ {

    include /config/nginx/proxy.conf;
    proxy_pass http://0.0.0.0:6880/;
    sub_filter_once off;
    sub_filter '/js/' '/aria/js/';
    sub_filter '/css/' '/aria/css/';
}

        location /aria/jsonrpc {
                proxy_pass http://0.0.0.0:6800/jsonrpc;
                proxy_http_version 1.1;
                proxy_set_header Upgrade $http_upgrade;
                proxy_set_header Connection "upgrade";
        }
```

Am I doing something wrong?

**Comment by LamGC** [comment]
`proxy_pass http://0.0.0.0:6800/jsonrpc;`
Maybe you should set it to `127.0.0.1`? As far as I know, `0.0.0.0` is only used for open access, not as a local address.

**Comment by P3TERX** [comment]
I haven't configured nginx in a long time, and based on past experience, I think you should remove `/jsonrpc`.
When configuring a web interface like AriaNg, you need to add subfolders.
![image](https://user-images.githubusercontent.com/25927179/108271964-8f742800-71ac-11eb-86e8-887dc06cce93.png)
