### ISSUE TITLE
base of  docker image can not be used in raspberry pi

### ISSUE THREAD

**Issue by phantasiae** [P3TERX/Aria2-Pro-Docker#27]
The docker image p3terx/s6-alpine can not used in raspberry pi.
So the aria2-pro image base on p3terx/s6-alpine can run in raspbery pi, but run `date` display `Sun Jan  0 00:100:4174038  1900`.
That make the image can not get each config file by web.
It can good running when replace the base image from p3terx/s6-alpine to p3terx/s6-debian.
Can you make an aria2-pro image with p3terx/s6-debian? Or I create a pull request? Or I fork a copy of code to edit?

**Comment by P3TERX** [comment]
I updated the image a few hours ago and tested it with no anomalies.
Based on your description, I looked for solutions that might work for you：https://github.com/alpinelinux/docker-alpine/issues/135#issuecomment-762397429

**Comment by qcgzxw** [comment]
Firstly, you need to download libseccomp2 package on [https://packages.debian.org/buster-backports/armhf/libseccomp2/download](https://packages.debian.org/buster-backports/armhf/libseccomp2/download)
then install it
FYI,it works on my pi.

**Comment by phantasiae** [comment]
I upgrade version of the libseccomp2 to 2.4.4, it is successful to run `date` .
Think you very much.
