### ISSUE TITLE
暂停下载任务再删除任务时，磁盘里面的文件不会被删除

### ISSUE THREAD

**Issue by hugohehuan** [P3TERX/Aria2-Pro-Docker#31]
系统：Open Media Vault 4.5 (Debian GNU/Linux 9.13 (stretch))
Docker：Docker version 19.03.14, build 5eb3275d40
aria-pro镜像信息："Created": "2021-01-15T08:30:44.426306122Z",
UI：AriaNG
...........................
不知道这个算不算bug……
或者是断点续传的逻辑所需？

检查了scpric.conf里面的内容，delete-on-xxx都是ture

当下载任务进行中，直接把任务删掉，文件是能被删掉的，日志记录如下：
> 02/17` 21:13:59 [[1;32mNOTICE[0m] Download GID#5f2a3ccdf25303e6 not complete: /downloads2/ubuntu-20.04.2-live-server-amd64.iso
> 02/17 21:13:59 [[1;32mNOTICE[0m] Serialized session to '/config/aria2.session' successfully.
> 02/17 21:14:00 [[1;32mINFO[0m] Download task removed, deleting files...
> removed '/downloads2/ubuntu-20.04.2-live-server-amd64.iso.aria2'
> removed '/downloads2/ubuntu-20.04.2-live-server-amd64.iso'
> 02/17 21:14:00 [[1;32mINFO[0m] General download task, skipped delete .torrent file.
> 02/17 21:14:00 [[1;32mINFO[0m] Deleting empty directory ...

由于我之前的习惯，删掉之前都是先暂停的，这个时候发现文件是没有被删掉的，日志中也没有相关条目：
> 02/17 21:14:29 [[1;32mNOTICE[0m] Download GID#4dab7df8eafec6b0 paused
> 02/17 21:14:30 [[1;32mNOTICE[0m] Serialized session to '/config/aria2.session' successfully.
> 02/17 21:14:34 [[1;32mNOTICE[0m] Serialized session to '/config/aria2.session' successfully.

**Comment by P3TERX** [comment]
![image](https://user-images.githubusercontent.com/25927179/108269082-72d5f100-71a8-11eb-9513-25723066085b.png)
