### ISSUE TITLE
请问是否支持 data volume？

### ISSUE THREAD

**Issue by Rangtian** [P3TERX/Aria2-Pro-Docker#37]
不然每次更新都要把 aria2-pro 跟 ariang 的各种参数重设一遍。。

**Comment by weifeng12x** [comment]
docker run -d \
  --name aria2-pro \
  --restart unless-stopped \
  --log-opt max-size=1m \
  -e PUID=$UID \
  -e PGID=$GID \
  -e UMASK_SET=022 \
  -e RPC_SECRET=<TOKEN> \
  -e RPC_PORT=6800 \
  -p 6800:6800 \
  -e LISTEN_PORT=6888 \
  -p 6888:6888 \
  -p 6888:6888/udp \
  -v $PWD/aria2-config:/config \
  -v $PWD/aria2-downloads:/downloads \
  p3terx/aria2-pro

 -v $PWD/aria2-config:/config \
  -v $PWD/aria2-downloads:/downloads \
这两行参数是你需要的吗？
