### ISSUE TITLE
I wonder if there is a way to check the network status

### ISSUE THREAD

**Issue by Pyrokine** [P3TERX/Aria2-Pro-Docker#46]
I added a dozen torrents tasks and each of them has tens of peers but none of them has download speed. Some of them are hot sources and can be downloaded by Thunder in high speed, so I wonder if there is a way to check the network status and find out whether there is something wrong or not. Thanks.

**Comment by P3TERX** [comment]
The best way is to download the Ubuntu ISO file
https://releases.ubuntu.com/20.04/ubuntu-20.04.5-desktop-amd64.iso.torrent
