### ISSUE TITLE
有些不明白为什么aria2 aria2ng要分两个docker

### ISSUE THREAD

**Issue by lalasou** [P3TERX/Aria2-Pro-Docker#47]
一键部署不是更方便
非得在多加一个aria2ng 
aria2pro 里面加入aria2ng 不就行了

**Comment by P3TERX** [comment]
本身就是两个东西，并非强关联性的，不是所有人都用 AriaNg ，而且不是每一台设备上都要单独部署一个。

**Comment by miuchan** [comment]
这本来就是两个软件，aria2本身是不带前端的，想要一键部署用docker-compose就可以了
