### ISSUE TITLE
如何阻止 Aria2 自动创建文件夹

### ISSUE THREAD

**Issue by mgxnore** [P3TERX/Aria2-Pro-Docker#48]
我是用树莓派下载到外接硬盘。

假设硬盘的挂载路径为/media/pi/MyDisk ， 下载路径是 /media/pi/MyDisk/Downloads ，有时移除外接硬盘或重启设备等硬盘未挂载的情况下，Aria2会自动创建 /media/pi/MyDisk/Downloads 空文件夹。

当我再插入硬盘时，硬盘的路径会变成 /media/pi/MyDisk1 ，用Aria2 下载也会下载到它自己创建的 /media/pi/MyDisk/Downloads 而不是外接硬盘内。

我还要先断开硬盘、删除  /media/pi/MyDisk 、重新插入硬盘最后重启docker才能恢复正常，太麻烦了！ 

有没有什么办法能阻止 Aria2 自动创建文件夹？当挂载硬盘后它能自动识别目录？

**Comment by carloswear** [comment]
建议再买个硬盘，这不是软件问题。
