### ISSUE TITLE
feature: Is that possible support portainer stack template ?

### ISSUE THREAD

**Issue by betgar** [P3TERX/Aria2-Pro-Docker#51]
Thank you for your work on this project. 
I used this on openmediavault，so i use [`portainer-ce`](https://documentation.portainer.io/v2.0/deploy/ceinstalldocker/) manage the docker containers.  When the `aria2-pro` update, I can update it very easy.
 `portainer-ce` also used `docker-compose` to deploy the containers, so the `docker-compose.yml` needs a litte changes to compatible with it. Such the `volume path` and the `networks` need to change.

**Comment by Kopi1984** [comment]
I use OMV too, and I just make that via stack, just copy the docker-compose.yml from the site, change info that you need to, then deploy the container.

**Comment by P3TERX** [comment]
I also use OMV, but I'm used to using the docker compose command line to start containers.
