### ISSUE TITLE
move.sh issue

### ISSUE THREAD

**Issue by XyNull** [P3TERX/Aria2-Pro-Docker#55]
move.sh cant move any thing to point directory, is this cause I use a diffrent volume?

I use volume1 as /downloads and volume2 as /fin
![图片](https://user-images.githubusercontent.com/19172206/131340916-27fb8d11-db08-44fa-a33c-676d49cec95e.png)

log:
Number of Files: 1

First File Path: /downloads/Dism++10.1.1002.1.zip

Task File Name: Dism++10.1.1002.1.zip

Task Path: /downloads/Dism++10.1.1002.1.zip

Aria2 Download Directory: /downloads

Custom Download Directory: /downloads

Source Path: /downloads/Dism++10.1.1002.1.zip

Destination Path: /fin

.aria2 File Path: null

-------------------------- [Task Infomation] --------------------------

mv: can't create '/fin/Dism++10.1.1002.1.zip': Permission denied

'/downloads/Dism++10.1.1002.1.zip' -> '/fin/Dism++10.1.1002.1.zip'

08/30 20:40:12 [ERROR] Move failed: /downloads/Dism++10.1.1002.1.zip

**Comment by zurica2013** [comment]
Just check the user and user group of those directories, most issues about failing to move, delete or execute files are caused by this reason. Just fixed that problem same as you guys
