### ISSUE TITLE
wallabag似乎会导致Aria2失去连接

### ISSUE THREAD

**Issue by i-iooi-i** [P3TERX/Aria2-Pro-Docker#60]
大佬，报告一个发现的神奇问题。我在群晖docker里用wallabag的官方镜像搭建了一个wallabag（ https://registry.hub.docker.com/r/wallabag/wallabag/ ）  并且反向代理设置为外网访问。

但是每次当我用域名+端口访问wallabag的页面的时候，Aria2就会出现无法连接的问题。然后我尝试把wallabag的端口名字换了很多个，情况还是相同，只要浏览器输入域名+端口访问wallabag，Aria2必然断联。解决方法就是清空浏览器数据，Aria2就会重新自动连接上了。但是再次浏览器输入域名+端口访问wallabag，Aria2就会再次失去连接。（备注：使用内网IP地址访问wallabag，Aria2就不存在掉连接的问题。）

![image](https://user-images.githubusercontent.com/1827701/140639463-a6b2448e-7604-415a-8d97-bfd24c0c641b.png)

当然我不知道这个问题是出在群晖，还是出在wallabag，还是出在Aria2。就是比较神奇，特来报告一下。若是大佬有时间也可以搭建wallabag来验证一下这个问题。再次感谢大佬对超级棒Aria2镜像的维护。

**Comment by akimolll** [comment]
Sorry~ 

我发现内网 IP+端口访问，Aria2 也会断连。
![image](https://user-images.githubusercontent.com/1827701/140639962-227fdfad-7ef8-46f0-ac11-3d768a91f6d3.png)

**Comment by akimolll** [comment]
破案了。

在群晖里为任何一个服务开启反向代理，只要勾选“启用HSTS”，当访问这个服务的时候，就会导致浏览器的Aria2失去连接。不是wallabag的问题。在Chrome与Edge里都存在这个问题。


![Snipaste_2021-11-08_08-26-51](https://user-images.githubusercontent.com/1827701/140667909-ea179f47-9e6c-424c-b0d9-5d873afffe6a.png)
