### ISSUE TITLE
下载目录被重置为nobody用户组问题

### ISSUE THREAD

**Issue by yugu91** [P3TERX/Aria2-Pro-Docker#64]
每次启动都会更改文件夹权限
请问我需要怎么修改，才能不是 nobody:nobody 呢？
进容器查看 aria2线程 用户也是 nobody

**Comment by mrbruce516** [comment]
用compose部署的吧 
echo $UID 和 $PID查看一下自己对应的id
- PUID=改成你自己的ID
- PGID=改成你自己的ID
重新compose即可

**Comment by sshuangliu** [comment]
> 用compose部署的吧 echo $UID 和 $PID查看一下自己对应的id
> 
> * PUID=改成你自己的ID
> * PGID=改成你自己的ID
>   重新compose即可

请教下，由于我是把Aria2的download目录挂载到nextcloud外部存储，而nextcloud的操作用户权限都是www-data www-data，
然后Aria 下载的文件权限都是nobody   nogroup，导致在nextcloud web界面无法删除文件，

请问如何吧aria 下载的文件的权限变更为www-data www-data/


3QQQQQQQ

**Comment by heddxh** [comment]
我觉得这里可能有问题：
https://github.com/P3TERX/Aria2-Pro-Docker/blob/e877015257c6ff0b5d653afbe15eaa62988e9cc8/rootfs/etc/cont-init.d/58-permissions#L16-L17

应该改成 `${PUID}:${PGID}` 吗？

**Comment by guojian0624** [comment]
我也遇到这个问题，黑群晖docker。
