### ISSUE TITLE
无限重启

### ISSUE THREAD

**Issue by smilence86** [P3TERX/Aria2-Pro-Docker#65]
pve虚拟的ubuntu20.04 ltsc，
  
`docker run -d \
  --name aria2 \
  --restart always \
  --log-opt max-size=1m \
  -e PUID=$UID \
  -e PGID=$GID \
  -e UMASK_SET=022 \
  -e RPC_SECRET=mySecret \
  -e RPC_PORT=6800 \
  -p 6800:6800 \
  -e LISTEN_PORT=6888 \
  -p 6888:6888 \
  -p 6888:6888/udp \
  -v /myPath/aria2/config:/config \
  -v /myPath/aria2/downloads:/downloads \
  p3terx/aria2-pro`

  
![image](https://user-images.githubusercontent.com/6102831/146868479-3a95642b-3c64-49f2-ab57-4e75acb27fe3.png)

**Comment by smilence86** [comment]
使用tag：202108221156正常，latest有问题。

**Comment by QiTianzu** [comment]
你好，我使用的系统是OpenVZ CentOS 7.9，也遇到了同样的情况，硬盘空间仅剩 500 M，下载时容器崩溃。不管是重启系统，删除容器和镜像后重装，还是重装 docker ，结果都一样，用 202108221156 也不行。
![image](https://user-images.githubusercontent.com/50047003/153209313-35250ee0-c6cd-4bb2-a2ce-e176688d9838.png)
