### ISSUE TITLE
-bash: TOKEN: 没有那个文件或目录

### ISSUE THREAD

**Issue by 392377870** [P3TERX/Aria2-Pro-Docker#67]
root@arm-64:~# docker run -d \
  --name aria2-pro \
  --restart unless-stopped \
  --log-opt max-size=1m \
  -e PUID=$UID \
  -e PGID=$GID \
  -e UMASK_SET=022 \
  -e RPC_SECRET=<TOKEN> \
  -e RPC_PORT=6800 \
  -p 6800:6800 \
  -e LISTEN_PORT=6888 \
  -p 6888:6888 \
  -p 6888:6888/udp \
  -v $PWD/aria2-config:/config \
  -v $PWD/aria2-downloads:/downloads \
  p3terx/aria2-pro
-bash: TOKEN: 没有那个文件或目录
这个怎么搞？ARMBIAN 的DOCKER安装

**Comment by wjf1547** [comment]
-e RPC_SECRET=<TOKEN> \
<TOKEN>就是密钥
可以修改为
-e RPC_SECRET=123456 \
