### ISSUE TITLE
重启Aria2后，历史 已经完成的记录  丢了。。。

### ISSUE THREAD

**Issue by sshuangliu** [P3TERX/Aria2-Pro-Docker#69]
![image](https://user-images.githubusercontent.com/38092313/150374250-35b89fac-da79-4594-a5e8-9a0c516beb73.png)

重启Aria2后，历史 已经完成的记录 丢了。。
这个是正常的吗？

谢谢

**Comment by guojian0624** [comment]
我发现重启后默认的Aria下载文件夹的权限被改掉了。好多用户的权限都没有了。

**Comment by P3TERX** [comment]
https://github.com/P3TERX/aria2.conf/blob/9286d0b30326f06fd2e12e06dda0841292f5b3f6/aria2.conf#L69
