### ISSUE TITLE
配置文件不生效

### ISSUE THREAD

**Issue by dawn-lc** [P3TERX/Aria2-Pro-Docker#71]
修改/etc/aria2下的aria2.conf dir项之后，重启容器发现容器内/config下的aria2.conf dir项并没有被修改。
而其他修改过的配置项都与宿主机文件同步正常。

Aria2-Pro:
  .....
    volumes:
      - /etc/aria2:/config
      - /data:/data
  .....

**Comment by P3TERX** [comment]
dir 固定是`/downloads`。你要设置下载目录直接改容器的目录映射。正确写法是：
```
volumes:
- /etc/aria2:/config
- /data:/downloads
```
也就是说下载文件到`/downloads`等于下载到你宿主机的`/data`
