### ISSUE TITLE
【优化/建议】日志输出是否可以精简空白行?

### ISSUE THREAD

**Issue by RyoLee** [P3TERX/Aria2-Pro-Docker#72]
![0](https://user-images.githubusercontent.com/1842651/154237294-db1995ff-f35b-447f-9053-d844e1ecd269.PNG)
![1](https://user-images.githubusercontent.com/1842651/154237300-36413c3a-65eb-4918-8093-cea4fbb1f7d8.PNG)
运行期间会生成大量的空白行日志,截图环境大概运行了5天左右,在没有什么下载的情况下跑出了155k+行的日志出来
![2](https://user-images.githubusercontent.com/1842651/154237832-e5d34f8f-814f-4939-8a94-84d5f238c226.PNG)
其中绝大部分都是空白行,是否可以适当优化?

**Comment by xiaoleichen** [comment]
这个感觉是aria2自己的问题。试过几个docker 容器都有个这个问题。我甚至试了一个空白alpine容器，直接在里面安装运行aria2，还是每隔十几分钟生成一堆空白日志。
我能想到唯一的办法是在docker run的时候加入 --log-driver=none。但是这样就彻底禁用log了。

**Comment by lhj18054979020** [comment]
作者还没进行优化吗，还是会打印巨多空行

**Comment by pansila** [comment]
这个是动态更新进度信息造成的，但是aria2没有提供关闭进度条的选项。不过有间接的办法在[这里](https://github.com/aria2/aria2/issues/1121)
