### ISSUE TITLE
无法下载。

### ISSUE THREAD

**Issue by ocean521** [P3TERX/Aria2-Pro-Docker#77]
安装的最新版DOCKER，然后在OP用户界面（非命令行）挂载了一个局域网内NAS的SMB共享文件夹（权限已经开放）作为下载目录，挂载目录是/mnt/xxx（不知道是否需要，XXX文件夹我在WINSCP里也给了权限），且将挂载目录作为下载目录。
出现的问题是我基本能确认挂载成功了（即我在NAS共享文件夹新建一个文件，然后可以在挂载目录里看见），但实际下载时，却下载失败和报错，是哪里操作的问题呢？谢谢指教

日志文件;
04/03 14:27:40 [ERROR] CUID#25 - Download aborted. URI=https://media-shengjingbank.todayir.com/20220330224802303810184432_tc.pdf
Exception: [AbstractCommand.cc:403] errorCode=16 URI=https://media-shengjingbank.todayir.com/20220330224802303810184432_tc.pdf
  -> [RequestGroup.cc:761] errorCode=16 Download aborted.
  -> [AbstractDiskWriter.cc:221] errNum=13 errorCode=16 Failed to open the file /downloads/20220330224802303810184432_tc.pdf, cause: Permission denied

04/03 14:27:40 [NOTICE] Download GID#81c6011374d6f67a not complete: /downloads/20220330224802303810184432_tc.pdf
04/03 14:27:40 [WARRING] Skip delete. File does not exist: /downloads/20220330224802303810184432_tc.pdf
04/03 14:27:40 [INFO] General download task, skipped delete .torrent file.
04/03 14:27:40 [INFO] Deleting empty directory ...

**Comment by wanghuisenior** [comment]
跟我的问题一样，权限不正常，还不知道怎么解决呢，有没有大佬瞅瞅啊

**Comment by ocean521** [comment]
不知道哪里的问题，一度可以下载，但是下载目录变成了“/overlay/upper/mnt/xxx”文件夹，而不是“/mnt/xxx”，但现在无法复现了。不知道当时是怎么搞得。
目前的状态就是彻底下载失败，点击开始就结束了。

**Comment by ocean521** [comment]
同时，还有一个问题，安装了aria2ng的DOCKER版本，网页里的下载目录是否需要配置啊，是参照aria2-pro简单配置成"/downloads"，还是如何设置，aria2-pro的conf文件里还是需要配置成"/downloads"，而不是实际目录吧

**Comment by wanghuisenior** [comment]
搞了好久解决了，权限问题，启动时指定参数puid和pgid为root用户的id，我原来用得是默认用户，权限不够

**Comment by ocean521** [comment]
如何指定参数puid和pgid为root用户的id啊？我是使用“ID docker”查询的

**Comment by wanghuisenior** [comment]
ssh连接服务器，输入id命令查询，如果你是docker面板启动容器，那就在环境里添加，如果你使用docker 命令启动，那就指定参数，看教程https://p3terx.com/archives/synology-nas-docker-advanced-tutorial-deploy-aria2-pro.html

**Comment by Delta-in-hub** [comment]
> 如何指定参数puid和pgid为root用户的id啊？我是使用“ID docker”查询的


❯ id root
uid=0(root) gid=0(root) 组=0(root)
