### ISSUE TITLE
请问如何更改默认下载目录 /downloads

### ISSUE THREAD

**Issue by GeorgeRudd** [P3TERX/Aria2-Pro-Docker#88]
https://github.com/P3TERX/Aria2-Pro-Docker/issues/59#issuecomment-963833122

这里进入容器修改了权限 请问有类似方法更改下载目录吗 每次重启都会被重置

**Comment by DDS-ALL** [comment]
你好，我这边基于大佬的镜像做了魔改，目前支持自定义下载目录，你可以尝试一下，如果有bug也可以向我提issues

这是地址:https://hub.docker.com/r/ddsderek/aria2-pro
