### ISSUE TITLE
docker image 大小突然增长

### ISSUE THREAD

**Issue by xyzeratul** [P3TERX/Aria2-Pro-Docker#94]
在unraid上面部署aria2-pro, 映射config目录在一块很小的SSD上面，docker.img也在同一块SSD上面，download目录映射在其他硬盘。

但在下载的时候，docker.img的大小突然增长，请问这是什么原因？是有什么数据要写在download目录以外吗？

**Comment by P3TERX** [comment]
没有，除非你把文件下载进了容器。
