### ISSUE TITLE
BT下载完成后在自动上传过程中，还是有大量下载流量

### ISSUE THREAD

**Issue by Anthony2cc** [P3TERX/Aria2-Pro-Docker#97]
Nethogs 信息如下：

USER     PROGRAM                                                                     DEV       SENT            RECEIVED       
root        13.107.136.9:443-Docker里显示的ip地址:53990                           0.000            12355.857   KB/sec
root        我VPS的地址:53990-13.107.136.9:443                                         2289.942      16.969         KB/sec

大佬能看看这是正常状态么？

**Comment by P3TERX** [comment]
统计信息延迟，很正常。
